services:
  backend:
    build: .
    container_name: curjos-backend
    ports:
      - "8000:80"
    env_file:
      - .env
  frontend:
    build: ./frontend
    container_name: curjos-frontend
    environment:
      API_URL: http://localhost:8000
    ports:
      - "3000:80"
    depends_on:
      - backend